/*
* generated by Xtext
*/
package org.makumba.devel.plugin.eclipse.mdd.ui.outline;

import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;
import org.makumba.devel.plugin.eclipse.mdd.editor.*;

/**
 * customization of the default outline structure
 * 
 */
public class MDDTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
	public boolean consumeNode(modifiers node){
		return false;
	}
	
	public boolean consumeNode(charType node){
		return false;
	}
	
	public boolean consumeNode(intEnum node){
		return false;
	}
	
	public boolean consumeNode(fieldType node){
		return false;
	}
	
	public boolean consumeNode(functionArgumentDeclaration node){
		return false;
	}
	
	public boolean consumeNode(functionBody node){
		return false;
	}
	
	public List<EObject> getChildren(functionDeclaration semanticNode) {
		return NO_CHILDREN;
	}
	
	public List<EObject> getChildren(validationRuleDeclaration semanticNode) {
		return NO_CHILDREN;
	}
	
	public List<EObject> getChildren(subFieldDeclaration semanticNode) {
		return NO_CHILDREN;
	}
	
	public List<EObject> getChildren(titleDeclaration semanticNode) {
		return NO_CHILDREN;
	}
	
	public List<EObject> getChildren(nativeValidationRuleDeclaration semanticNode) {
		return NO_CHILDREN;
	} 
	
}
