/*
 * generated by Xtext
 */
package org.makumba.devel.plugin.eclipse.mdd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.syntaxcoloring.antlr.AbstractAntlrTokenToAttributeIdMapper;
import org.makumba.devel.plugin.eclipse.mdd.ui.syntaxcoloring.AntlrTokenToAttributeIdMapper;
import org.makumba.devel.plugin.eclipse.mdd.ui.syntaxcoloring.SemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MDDUiModule extends org.makumba.devel.plugin.eclipse.mdd.ui.AbstractMDDUiModule {
	public MDDUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends AbstractAntlrTokenToAttributeIdMapper>
		bindAbstractAntlrTokenToAttributeIdMapper() {
			return AntlrTokenToAttributeIdMapper.class ;
		}
	
	public Class<? extends ISemanticHighlightingCalculator>
	bindISemanticHiglightingCalculator() {
		return SemanticHighlightingCalculator.class ;
	}
	
}
